name: Dev release

on:
  push:
    tags: '**'

concurrency:
  group: ${{ github.ref_name }}

jobs:
  dev-release:
    uses: digabi/workflows-common/.github/workflows/digabi2-companion-app-dev-release.yml@4ec7a0650fabcced0f93f871e52d08dfd1702a9d
    with:
      app-name: geogebra
      aws-access-role: GeogebraGithubActionsAccessRole
    secrets: inherit
