name: Manual production release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
        type: string

concurrency:
  group: ${{ inputs.tag }}
  
jobs:
  release:
    uses: digabi/workflows-common/.github/workflows/digabi2-companion-app-prod-release.yml@4ec7a0650fabcced0f93f871e52d08dfd1702a9d
    with:
      app-name: geogebra
      aws-access-role: GeogebraGithubActionsAccessRole
      tag: ${{ inputs.tag }}
    secrets: inherit
