name: Manual production release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
        type: string

concurrency:
  group: ${{ inputs.tag }}

jobs:
  release:
    uses: digabi/workflows-common/.github/workflows/digabi2-companion-app-prod-release.yml@cbc4a31631cca4538bbbeddba0a71ad0dd845b28
    with:
      app-name: geogebra
      aws-access-role: GeogebraGithubActionsAccessRole
      tag: ${{ inputs.tag }}
    secrets: inherit
